### ISSUE TITLE
Some error with the hero ids

### ISSUE THREAD

**Issue by fISHxd** [jonghwanhyeon/overwatch-stats#4]
I guess it has something to do with the addition of Brigitte, I'm not sure tho. 
(code is `stats = overwatch.stats.query('pc', 'eu',  'fISH#21390')`)

File "...\overwatch\stats\__init__.py", line 176, in query
    time_played_ratios = extract_time_played_ratios(tree, mode)
  File "...\overwatch\stats\__init__.py", line 121, in extract_time_played_ratios
    hero = inverted_hero_category_ids[match.group(1)]
KeyError: '0x02E0000000000195'

**Comment by jonghwanhyeon** [comment]
Please update the package to the latest version! This package requires an update every time a new hero appears.
