### ISSUE TITLE
AttributeError in extractors

### ISSUE THREAD

**Issue by dOdEcadillion** [jonghwanhyeon/overwatch-stats#5]
This error occurs whenever I make a basic query.

```python
File "...\overwatch\stats\extractors.py", line 39, in extract_level
    match = re.search(r'/playerlevelrewards/(0x[0-9A-Z]+)_Border', level.get('style'))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jonghwanhyeon** [comment]
It works for my battle tag `현종환#3104`. It would be helpful if you can tell me your battle tag.

**Comment by dOdEcadillion** [comment]
I restarted my computer and just ran the query again and it ran with no problems...
I was messing with my dev environments before I had run the script so maybe something funky happened while I was doing that. Other than that, not sure what happened since I didn't change anything code wise.
Anyways, thank you for the reply. Sorry to bother.
